fix: prevents putting meaningless tasks into the queue
oat-sa/extension-tao-advanced-search pull request #29
Opened 2021-06-08 09:20 UTC by boajer

2021-06-09 07:59 UTC, gabrielfs7 commented on model/Index/Service/ResultIndexer.php
> +        }
```suggestion
        }
        
```

2021-06-09 08:00 UTC, gabrielfs7 commented on tests/Unit/Index/Service/ResultIndexerTest.php
> +    /** @var AdvancedSearchChecker|MockObject  */
PSR + our code style agreement

```suggestion

    /** @var AdvancedSearchChecker|MockObject  */
```

2021-06-09 08:02 UTC, gabrielfs7 requested changes
What about the other indexers in this repository?

2021-06-10 08:16 UTC, boajer commented
> What about the other indexers in this repository?

But `\oat\taoAdvancedSearch\model\Index\Service\ResultIndexer` so far the only existing implementation of `\oat\taoAdvancedSearch\model\Index\Service\IndexerInterface`

2021-06-10 12:52 UTC, chinnu-focaloid approved these changes
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [X] Acceptance criteria are respected
- [X] Pull request title and description are meaningful

2021-06-11 06:03 UTC, gabrielfs7 approved these changes

2021-06-11 06:04 UTC, gabrielfs7 commented
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful

2021-07-05 04:58 UTC, merged